name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Report version
      run: dart --version
    - name: Install dependencies
      run: dart pub get
    - name: Check formatting
      # TODO: Change this once https://github.com/dart-lang/sdk/issues/44023 is fixed
      run: ./.github/scripts/check_formatting.sh
    - name: Analyze code
      run: dart analyze

  test:
    needs: analyze
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    container:
      image: google/dart:latest

    steps:
    - name: Run tests
      run: dart test
